### ISSUE TITLE
Need help with Java build errors

### ISSUE THREAD

**Issue by TobiasNx** [pkiraly/qa-catalogue#503]
In my attempt to add new elements for a hbz catalogue somehow there were a couple of java tests that were failing.
We could solve them and could understand the relation to the changes I added.

But one test  and an error we do not understand 

https://github.com/hbz/qa-catalogue/pull/1#issuecomment-2298942849

```
 Results :

Failed tests:   testPatternMatchingWithSubfield(de.gwdg.metadataqa.marc.analysis.bl.UseCaseTest): expected:<[110$e, 111$e, 100$e, 700$e, 710$e, 711$e, 720$e, 751$e, 752$e, 775$e, 788$e]> but was:<[100$e, 110$e, 111$e, 700$e, 710$e, 711$e, 720$e, 751$e, 752$e, 775$e, 788$e]>

Tests in error: 
  testListTag(de.gwdg.metadataqa.marc.utils.MarcTagListerTest): Cannot invoke "de.gwdg.metadataqa.marc.definition.structure.DataFieldDefinition.getTag()" because "definition" is null
```

Build here: https://github.com/hbz/qa-catalogue/actions/runs/10472986275/job/29003791025#step:4:16623

@pkiraly or @nichtich can you help us?

Ping @Phu2

**Comment by pkiraly** [comment]
@TobiasNx I am checking it.

The root of the second is that in de.gwdg.metadataqa.marc.definition.tags.hbztags.TagHOL and de.gwdg.metadataqa.marc.definition.tags.hbztags.TagMNG you missed cardinality flag from a particular subfield:

```
      "c", "Updated by subfield",
```
it should be
```
      "c", "Updated by subfield", "R",
```
or
```
      "c", "Updated by subfield", "NR",
```
This two errors prevents the initialization of these tags, and it causes another issue when we calculate the number of metadata elements. I do not know the root of other issue, but it can be easily fixed by changing the order of expected elements.

Here I send you a  patch file with the necessary changes
[need-help-with-java-build-errors-503.txt](https://github.com/user-attachments/files/16690104/need-help-with-java-build-errors-503.txt)

Plese check it. You can apply it with

```
git apply need-help-with-java-build-errors-503.txt
```

**Comment by TobiasNx** [comment]
Thanks
